version: "3.9"

services:
  db:
    image: postgres:16
    container_name: bi_ml_postgres
    environment:
      POSTGRES_DB: bi_ml
      POSTGRES_USER: bi_user
      POSTGRES_PASSWORD: bi_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
